export const EventAction = {
  CREATE_EVENT: 'CREATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  DELETE_ALL_EVENTS: 'DELETE_ALL_EVENTS',
};


export const OperationLogsAction = {
  ADD_OPERATION_LOG: 'ADD_OPERATION_LOG',
  DELETE_ALL_OPERATION_LOGS: 'DELETE_ALL_OPERATION_LOGS'
}